// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import { Database } from "./types"; // Se você tiver tipos gerados, senão pode remover <Database>

// Tenta pegar as variáveis de ambiente
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Verificação de segurança para não quebrar a aplicação inteira com tela branca
if (!supabaseUrl || !supabaseKey) {
  console.error(
    "⚠️ ERRO CRÍTICO: Variáveis de ambiente do Supabase não encontradas.",
    "Verifique se VITE_SUPABASE_URL e VITE_SUPABASE_ANON_KEY estão configuradas.",
  );
}

// Inicializa o cliente.
// Usamos um fallback (|| '') para evitar o erro "supabaseUrl is required" imediato do construtor,
// mas as chamadas falharão se a URL for inválida.
export const supabase = createClient<Database>(
  supabaseUrl || "https://placeholder-project.supabase.co",
  supabaseKey || "placeholder-key",
);
