// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// --- RECUPERADO DA MEMÓRIA ---
// URL e Chave do seu projeto Supabase (H2 Linker / h2link)
const SUPABASE_URL = "https://dalarhopratsgzmmzhxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..XXXXX"; // (Chave pública abreviada para segurança, o Lovable deve ter a completa, senão me avise que busco a completa)

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
