
-- Add comprehensive job details to sponsored_jobs for the structured create flow
ALTER TABLE public.sponsored_jobs
ADD COLUMN IF NOT EXISTS visa_type text DEFAULT 'H-2B',
ADD COLUMN IF NOT EXISTS employer_legal_name text,
ADD COLUMN IF NOT EXISTS city text,
ADD COLUMN IF NOT EXISTS state text,
ADD COLUMN IF NOT EXISTS hourly_wage numeric,
ADD COLUMN IF NOT EXISTS overtime_rate numeric,
ADD COLUMN IF NOT EXISTS pay_frequency text DEFAULT 'weekly',
ADD COLUMN IF NOT EXISTS bonuses text,
ADD COLUMN IF NOT EXISTS additional_compensation text,
ADD COLUMN IF NOT EXISTS housing_provided boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS transportation_provided boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS visa_fee_reimbursement boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS meals_provided boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS daily_meal_cost numeric,
ADD COLUMN IF NOT EXISTS deductions_standard boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS deductions_additional text,
ADD COLUMN IF NOT EXISTS flsa_compliant boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS english_level text DEFAULT 'not_required',
ADD COLUMN IF NOT EXISTS prior_experience_required boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS lifting_weight_lbs integer,
ADD COLUMN IF NOT EXISTS skill_level text DEFAULT 'entry',
ADD COLUMN IF NOT EXISTS primary_duties text,
ADD COLUMN IF NOT EXISTS equipment_used text,
ADD COLUMN IF NOT EXISTS work_environment text,
ADD COLUMN IF NOT EXISTS training_provided boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS additional_notes text,
ADD COLUMN IF NOT EXISTS compliance_acknowledged boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS source_type text DEFAULT 'platform',
ADD COLUMN IF NOT EXISTS dol_case_number text,
ADD COLUMN IF NOT EXISTS is_claimed boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS num_positions integer DEFAULT 1;
